name: Test casadi libs across platforms

on:
  push:
  workflow_dispatch:

jobs:
  test_casadi_libs:
    name: List contents of casadi site-packages dir across platforms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install casadi
        run: python -m pip install casadi

      - name: List casadi site packages directory contents
        run: python -c "import importlib.util; import os; casadi_dir = next(iter(importlib.util.find_spec('casadi').submodule_search_locations)); print(os.listdir(casadi_dir))"
